# Generated by Django 6.0.4 on 2026-08-24 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('REVISION_PENDIENTE', 'Revisión Pendiente'), ('APROBACION', 'Aprobado'), ('RECHAZO', 'Rechazado'), ('ALERTA_PRESUPUESTO', 'Alerta de Presupuesto'), ('SISTEMA', 'Mensaje del Sistema')], default='REVISION_PENDIENTE', max_length=30, verbose_name='Tipo de Notificación')),
                ('enlace', models.CharField(blank=True, max_length=255, null=True, verbose_name='Enlace de Acción')),
                ('leido', models.BooleanField(default=False, verbose_name='¿Leído?')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Destino')),
                ('usuario_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Origen')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
