# Generated by Django 5.2.17 on 2026-08-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('monto_ejecutado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Ejecutado')),
                ('fecha_gasto', models.DateField(verbose_name='Fecha del Gasto')),
                ('comprobante_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° de Comprobante')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
            ],
            options={
                'verbose_name': 'Gasto Ejecutado',
                'verbose_name_plural': 'Gastos Ejecutados',
                'db_table': 'ejecucion_gasto',
            },
        ),
    ]
