# Generated by Django 5.2.17 on 2026-08-19 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ejecucion', '0001_initial'),
        ('memorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='detalle_memoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='memorias.detallepresupuestomemoria', verbose_name='Detalle de Memoria'),
        ),
    ]
