# Generated by Django 5.2.17 on 2026-08-31 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejecucion', '0004_remove_gasto_detalle_memoria_gasto_memoria'),
        ('memorias', '0010_detallepresupuestomemoria_total_programado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='memoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='memorias.memoriacalculo', verbose_name='Memoria de Cálculo'),
        ),
    ]
