# Generated by Django 5.2.17 on 2026-09-01 16:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejecucion', '0005_alter_gasto_memoria'),
        ('memorias', '0010_detallepresupuestomemoria_total_programado'),
        ('organizacional', '0003_delete_rol_alter_area_options_alter_programa_options_and_more'),
        ('planificacion', '0002_tarea_estado'),
        ('presupuestos', '0003_alter_partida_codigo_alter_partida_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificacionPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('codigo_certificacion', models.CharField(max_length=100, verbose_name='Nº Certificación POA')),
                ('numero_oficio_solicitud', models.CharField(max_length=100, verbose_name='Nº Oficio de Solicitud')),
                ('fecha', models.DateField(verbose_name='Fecha de Emisión')),
                ('version', models.CharField(default='Versión 1: 2026', max_length=50, verbose_name='Versión')),
                ('partida_literal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Partida Presupuestaria (Texto)')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto Solicitado')),
                ('concepto_gasto', models.TextField(blank=True, null=True, verbose_name='Concepto / Objeto del Gasto')),
                ('notas', models.TextField(blank=True, default='Notas: El presente documento da a conocer únicamente que la solicitud en mención se encuentra programada en alineación a la Acción de Mediano Plazo (PEE) y la Acción de Corto Plazo (POA) registrados en el Plan Operativo Anual. Los aspectos presupuestarios y de contratación corresponden al área solicitante y se encuentran en el marco de las atribuciones y competencias de la Gerencia de Asuntos Administrativos EPTAM y sus instancias correspondientes según el D.S. Nº 0181 y normativa vigente relacionada.', verbose_name='Notas Legales / Aclaratorias')),
                ('solicitante_nombre', models.CharField(blank=True, default='', max_length=150, verbose_name='Solicitado por (Nombre)')),
                ('solicitante_cargo', models.CharField(blank=True, default='', max_length=150, verbose_name='Solicitado por (Cargo)')),
                ('elaborador_nombre', models.CharField(blank=True, default='', max_length=150, verbose_name='Elaborado por (Nombre)')),
                ('elaborador_cargo', models.CharField(blank=True, default='', max_length=150, verbose_name='Elaborado por (Cargo)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones_poa', to='organizacional.area', verbose_name='Unidad Solicitante / Área')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones_poa', to='presupuestos.gestion', verbose_name='Gestión')),
                ('memoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificaciones_poa', to='memorias.memoriacalculo', verbose_name='Memoria de Cálculo')),
                ('operaciones', models.ManyToManyField(blank=True, related_name='certificaciones_poa', to='planificacion.operacion', verbose_name='Operaciones POA Asociadas')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificaciones_poa', to='presupuestos.partida', verbose_name='Partida Presupuestaria')),
            ],
            options={
                'verbose_name': 'Certificación POA',
                'verbose_name_plural': 'Certificaciones POA',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
