# Generated by Django 5.2.17 on 2026-09-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejecucion', '0006_certificacionpoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacionpoa',
            name='observacion_planificacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación de Planificación'),
        ),
        migrations.AlterField(
            model_name='certificacionpoa',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador (Gerencia)'), ('PENDIENTE_PLANIFICACION', 'Enviado a Planificación'), ('APROBADO', 'Aprobado por Planificación'), ('OBSERVADO', 'Observado / Devuelto'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=30, verbose_name='Estado'),
        ),
    ]
