# Generated by Django 5.2.17 on 2026-08-17 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacional', '0001_initial'),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraspasoPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto')),
                ('justificacion', models.TextField(verbose_name='Justificación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Aprobación')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos', to='organizacional.area', verbose_name='Área')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos', to='presupuestos.gestion', verbose_name='Gestión')),
                ('partida_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_entrada', to='presupuestos.asignacionpartida', verbose_name='Partida Destino')),
                ('partida_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_salida', to='presupuestos.asignacionpartida', verbose_name='Partida Origen')),
            ],
            options={
                'verbose_name': 'Traspaso de Partida',
                'verbose_name_plural': 'Traspasos de Partidas',
            },
        ),
    ]
