# Generated by Django 5.2.17 on 2026-08-17 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traspasos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traspasopartida',
            name='usuario_aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspasos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobador'),
        ),
        migrations.AddField(
            model_name='traspasopartida',
            name='usuario_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
    ]
