# Generated by Django 5.2.17 on 2026-08-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['codigo'], 'verbose_name': 'Área / Gerencia / Unidad', 'verbose_name_plural': 'Áreas / Gerencias / Unidades'},
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ['codigo'], 'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'ordering': ['nombre'], 'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
    ]
