# Generated by Django 5.2.17 on 2026-08-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0002_rol_alter_area_options_alter_programa_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Área / Gerencia / Unidad', 'verbose_name_plural': 'Áreas / Gerencias / Unidades'},
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
    ]
