# Generated by Django 6.0.4 on 2026-08-24 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacional', '0003_delete_rol_alter_area_options_alter_programa_options_and_more'),
        ('presupuestos', '0003_alter_partida_codigo_alter_partida_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionMedianoPlazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código AMP')),
                ('descripcion', models.TextField(verbose_name='Descripción / Objetivo Estratégico PEI')),
                ('periodo_inicio', models.PositiveIntegerField(default=2026, verbose_name='Año Inicio Quinquenio')),
                ('periodo_fin', models.PositiveIntegerField(default=2030, verbose_name='Año Fin Quinquenio')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_mediano_plazo', to='organizacional.programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Acción a Mediano Plazo (PEI)',
                'verbose_name_plural': 'Acciones a Mediano Plazo (PEI)',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='AccionCortoPlazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código ACP')),
                ('descripcion', models.TextField(verbose_name='Descripción / Objetivo de Gestión POA')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('gestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_corto_plazo', to='presupuestos.gestion', verbose_name='Gestión POA')),
                ('accion_mediano_plazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_corto_plazo', to='planificacion.accionmedianoplazo', verbose_name='Acción a Mediano Plazo (PEI)')),
            ],
            options={
                'verbose_name': 'Acción a Corto Plazo (POA)',
                'verbose_name_plural': 'Acciones a Corto Plazo (POA)',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código Operación')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Operación')),
                ('es_contratacion', models.BooleanField(default=True, verbose_name='Aplica para Contrataciones/Compras')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('accion_corto_plazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='planificacion.accioncortoplazo', verbose_name='Acción a Corto Plazo (POA)')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='organizacional.area', verbose_name='Área / Gerencia / Unidad')),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=30, verbose_name='Código Tarea')),
                ('descripcion', models.TextField(verbose_name='Descripción de Tarea / Detalle TAMEP')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='planificacion.operacion', verbose_name='Operación')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['codigo'],
            },
        ),
    ]
