# Generated by Django 6.0.4 on 2026-08-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
