# Generated by Django 5.2.17 on 2026-08-17 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacional', '0001_initial'),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('justificacion', models.TextField(verbose_name='Justificación')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO_REVISION', 'Enviado para Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EJECUTADO', 'Ejecutado')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('observacion_revision', models.TextField(blank=True, null=True, verbose_name='Observación Revisión')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Aprobación')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorias_calculo', to='presupuestos.gestion', verbose_name='Gestión')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorias_calculo', to='organizacional.seccion', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Memoria de Cálculo',
                'verbose_name_plural': 'Memorias de Cálculo',
            },
        ),
        migrations.CreateModel(
            name='DetallePresupuestoMemoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('estado_ejecucion', models.CharField(choices=[('PENDIENTE', 'Pendiente de Gasto'), ('EJECUTADO', 'Gasto Realizado / Ejecutado'), ('NO_EJECUTADO', 'No Ejecutado / Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado Gasto')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_memoria', to='presupuestos.partida', verbose_name='Partida')),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='memorias.memoriacalculo', verbose_name='Memoria')),
            ],
            options={
                'verbose_name': 'Detalle de Presupuesto en Memoria',
                'verbose_name_plural': 'Detalles de Presupuesto en Memorias',
            },
        ),
        migrations.CreateModel(
            name='RegistroMemoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('tipo_participacion', models.CharField(choices=[('ELABORADOR', 'Elaborador de la Memoria'), ('EJECUTOR', 'Responsable de Ejecutar la Tarea'), ('REVISOR_APROBADOR', 'Revisor / Aprobador')], max_length=25, verbose_name='Participación')),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='memorias.memoriacalculo', verbose_name='Memoria')),
            ],
            options={
                'verbose_name': 'Participante de Memoria',
                'verbose_name_plural': 'Participantes de Memorias',
            },
        ),
    ]
