# Generated by Django 5.2.17 on 2026-08-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorias', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepresupuestomemoria',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
