# Generated by Django 5.2.17 on 2026-08-21 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorias', '0003_alter_detallepresupuestomemoria_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraspasoPresupuestario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('estado', models.CharField(choices=[('APROBADO', 'Aprobado')], default='APROBADO', max_length=20, verbose_name='Estado')),
                ('memoria_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_entrada', to='memorias.memoriacalculo', verbose_name='Memoria Destino')),
                ('memoria_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_salida', to='memorias.memoriacalculo', verbose_name='Memoria Origen')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspasos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registro')),
            ],
            options={
                'verbose_name': 'Traspaso Presupuestario',
                'verbose_name_plural': 'Traspasos Presupuestarios',
            },
        ),
    ]
