# Generated by Django 5.2.17 on 2026-08-21 03:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorias', '0004_traspasopresupuestario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepresupuestomemoria',
            name='saldo_disponible',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Saldo Disponible'),
        ),
        migrations.AddField(
            model_name='detallepresupuestomemoria',
            name='total_ejecutado',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Total Ejecutado'),
        ),
        migrations.AddField(
            model_name='memoriacalculo',
            name='monto_entrante',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Monto Entrante (Traspasos)'),
        ),
        migrations.AddField(
            model_name='memoriacalculo',
            name='monto_saliente',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Monto Saliente (Traspasos)'),
        ),
        migrations.AddField(
            model_name='memoriacalculo',
            name='saldo_disponible',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Saldo Disponible'),
        ),
        migrations.AddField(
            model_name='memoriacalculo',
            name='total_ejecutado',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Total Ejecutado'),
        ),
        migrations.AddField(
            model_name='memoriacalculo',
            name='total_presupuestado',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Total Presupuestado'),
        ),
    ]
