# Generated by Django 6.0.4 on 2026-08-24 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorias', '0005_detallepresupuestomemoria_saldo_disponible_and_more'),
        ('planificacion', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoriacalculo',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memorias_calculo', to='planificacion.operacion', verbose_name='Operación POA'),
        ),
        migrations.AlterField(
            model_name='memoriacalculo',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_GERENCIA', 'Pendiente de Gerencia'), ('APROBADO_GERENCIA', 'Aprobado por Gerencia'), ('PENDIENTE_PLANIFICACION', 'Pendiente de Planificación'), ('APROBADO_PLANIFICACION', 'Alineado por Planificación'), ('APROBADO_FINANZAS', 'Aprobado por Finanzas'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=30, verbose_name='Estado'),
        ),
    ]
