# Generated by Django 6.0.4 on 2026-08-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorias', '0006_memoriacalculo_operacion_alter_memoriacalculo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoriacalculo',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Aceptación / Rechazo / Observación'),
        ),
    ]
