# Generated by Django 6.0.4 on 2026-08-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorias', '0007_memoriacalculo_motivo_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoriacalculo',
            name='es_contratacion',
            field=models.BooleanField(default=False, verbose_name='¿Corresponde a Contrataciones?'),
        ),
    ]
