# Generated by Django 5.2.17 on 2026-09-24 19:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorias', '0010_detallepresupuestomemoria_total_programado'),
        ('organizacional', '0003_delete_rol_alter_area_options_alter_programa_options_and_more'),
        ('presupuestos', '0003_alter_partida_codigo_alter_partida_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificacionPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('TRASPASO_INTRA_AREA', 'Traspaso Intra-Área'), ('INCREMENTO', 'Incremento Presupuestario'), ('DISMINUCION', 'Disminución Presupuestaria')], default='TRASPASO_INTRA_AREA', max_length=30, verbose_name='Tipo')),
                ('motivo', models.TextField(verbose_name='Motivo / Justificación')),
                ('total_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto Compensado')),
                ('estado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('ANULADO', 'Anulado')], default='APROBADO', max_length=20, verbose_name='Estado')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones_presupuestarias', to='organizacional.area', verbose_name='Área')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones_presupuestarias', to='presupuestos.gestion', verbose_name='Gestión')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registro')),
            ],
            options={
                'verbose_name': 'Modificación Presupuestaria',
                'verbose_name_plural': 'Modificaciones Presupuestarias',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleModificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('tipo_movimiento', models.CharField(choices=[('DISMINUCION', 'Disminución (Cede fondos)'), ('INCREMENTO', 'Incremento (Recibe fondos)')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto')),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_modificacion', to='memorias.memoriacalculo', verbose_name='Memoria de Cálculo')),
                ('modificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='memorias.modificacionpresupuestaria', verbose_name='Modificación Presupuestaria')),
            ],
            options={
                'verbose_name': 'Detalle de Modificación Presupuestaria',
                'verbose_name_plural': 'Detalles de Modificación Presupuestaria',
            },
        ),
    ]
