# Generated by Django 5.2.17 on 2026-08-17 19:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('anio', models.PositiveIntegerField(unique=True, verbose_name='Año de Gestión')),
                ('estado', models.CharField(choices=[('FORMULACION', 'En Formulación'), ('VIGENTE', 'Vigente'), ('CERRADA', 'Cerrada')], default='FORMULACION', max_length=20, verbose_name='Estado')),
                ('fecha_aprobacion_ministerio', models.DateField(blank=True, null=True, verbose_name='Fecha Aprobación Ministerial')),
            ],
            options={
                'verbose_name': 'Gestión',
                'verbose_name_plural': 'Gestiones',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('clase', models.CharField(choices=[('GASTO_CORRIENTE', 'Gasto Corriente'), ('GASTO_CAPITAL', 'Gasto de Capital / Inversión')], default='GASTO_CORRIENTE', max_length=25, verbose_name='Clase')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Partida Presupuestaria',
                'verbose_name_plural': 'Partidas Presupuestarias',
                'unique_together': {('codigo', 'clase')},
            },
        ),
        migrations.CreateModel(
            name='PresupuestoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('techo_asignado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Techo Asignado')),
                ('sobrante_gestion_anterior', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Sobrante Gestión Anterior')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='organizacional.area', verbose_name='Área')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_area', to='presupuestos.gestion', verbose_name='Gestión')),
            ],
            options={
                'verbose_name': 'Presupuesto de Área',
                'verbose_name_plural': 'Presupuestos de Áreas',
                'unique_together': {('gestion', 'area')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto Inicial')),
                ('monto_modificaciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Modificaciones (+/-)')),
                ('monto_vigente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto Vigente')),
                ('monto_comprometido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto Comprometido')),
                ('monto_disponible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto Disponible')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='presupuestos.partida', verbose_name='Partida')),
                ('presupuesto_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_partida', to='presupuestos.presupuestoarea', verbose_name='Presupuesto Área')),
            ],
            options={
                'verbose_name': 'Asignación de Partida',
                'verbose_name_plural': 'Asignaciones de Partidas',
                'unique_together': {('presupuesto_area', 'partida')},
            },
        ),
    ]
