# Generated by Django 5.2.17 on 2026-08-19 15:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('anio', models.PositiveIntegerField(unique=True, verbose_name='Año de Gestión')),
                ('estado', models.CharField(choices=[('FORMULACION', 'En Formulación'), ('CERRADO_FORMULACION', 'Formulación Cerrada'), ('EN_EJECUCION', 'En Ejecución'), ('FINALIZADO', 'Finalizado')], default='FORMULACION', max_length=25, verbose_name='Estado')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre de Formulación')),
            ],
            options={
                'verbose_name': 'Gestión',
                'verbose_name_plural': 'Gestiones',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('clase', models.CharField(choices=[('GASTO_CORRIENTE', 'Gasto Corriente'), ('GASTO_CAPITAL', 'Gasto de Capital / Inversión')], default='GASTO_CORRIENTE', max_length=25, verbose_name='Clase')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Activa'))
            ],
            options={
                'verbose_name': 'Partida Presupuestaria',
                'verbose_name_plural': 'Partidas Presupuestarias',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Inicial')),
                ('monto_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Actual (Disponible)')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20, verbose_name='Estado')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='organizacional.area', verbose_name='Área')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_area', to='presupuestos.gestion', verbose_name='Gestión')),
            ],
            options={
                'verbose_name': 'Presupuesto de Área',
                'verbose_name_plural': 'Presupuestos de Áreas',
                'unique_together': {('gestion', 'area')},
            },
        ),
    ]
