# Generated by Django 5.2.17 on 2026-08-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='clase',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], default='EGRESO', max_length=25, verbose_name='Clase'),
        ),
    ]
