# Generated by Django 5.2.17 on 2026-08-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_alter_partida_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterUniqueTogether(
            name='partida',
            unique_together={('codigo', 'clase')},
        ),
    ]
